services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  StarterTeam\StarterNessa\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Resource/Interrupter.php'
      - '../Classes/Resource/InterrupterReference.php'

  StarterTeam\StarterNessa\Resource\InterrupterCollector:
    public: true
